# Default values for app-chart.
frontend:
  replicaCount: 1
  image:
    repository: <your-registry>.azurecr.io/lab03/frontend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: <your-registry>.azurecr.io/lab03/backend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080